export const restaurants = [
  {
    id: 0,
    name: "McDonald's",
    logo: "https://www.mcdonalds.com.br/images/layout/mcdonalds-logo-bg-red.png",
    deliveryTime: "30-40 min",
    deliveryFee: "R$ 11,58",
    rating: 4.5,
    categories: ["Hamburgueria", "Fast Food"],
    paymentMethods: ["Dinheiro", "Cartão de Crédito", "Cartão de Débito"],
  },
  {
    id: 1,
    name: "Burguer King",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_9SmOVRcVzHvi5n01H8cuVbq4E3E6T9CJ94x0UmVepjRRa1mUQni6PE4UX2kogmPcWmo&usqp=CAU",
    deliveryTime: "30-40 min",
    deliveryFee: "R$ 5,00",
    rating: 4.5,
    categories: ["Hamburgueria", "Fast Food"],
    paymentMethods: ["Dinheiro", "Cartão de Crédito", "Cartão de Débito"],
  },
  {
    id: 2,
    name: "Subway",
    logo: "https://www.cidademarketing.com.br/marketing/wp-content/uploads/2022/04/maca_subway.png",
    deliveryTime: "30-40 min",
    deliveryFee: "Grátis",
    rating: 4.5,
    categories: ["Hamburgueria", "Fast Food"],
    paymentMethods: ["Dinheiro", "Cartão de Crédito", "Cartão de Débito"],
  },
  {
    id: 3,
    name: "KFC",
    logo: "https://i.pinimg.com/originals/aa/92/89/aa9289de1ed2865bccd7c7457f246482.jpg",
    deliveryTime: "30-40 min",
    deliveryFee: "R$ 2,50",
    rating: 4.5,
    categories: ["Frango Frito", "Fast Food"],
    paymentMethods: ["Dinheiro", "Cartão de Crédito", "Cartão de Débito"],
  },
  {
    id: 4,
    name: "Tokoku Fudidin",
    logo: "https://images-platform.99static.com/gn0vO61DTJPmSMVNtkyILaHmHD0=/96x96:864x864/500x500/top/smart/99designs-contests-attachments/72/72448/attachment_72448353",
    deliveryTime: "30-40 min",
    deliveryFee: "Grátis",
    rating: 4.5,
    categories: ["Sushi", "Japonesa"],
    paymentMethods: ["Dinheiro", "Cartão de Crédito", "Cartão de Débito"],
  },
  {
    id: 5,
    name: "Sushizen",
    logo: "https://images-platform.99static.com/gn0vO61DTJPmSMVNtkyILaHmHD0=/96x96:864x864/500x500/top/smart/99designs-contests-attachments/72/72448/attachment_72448353",
    deliveryTime: "30-40 min",
    deliveryFee: "R$ 5,00",
    rating: 4.5,
    categories: ["Sushi", "Japonesa"],
    paymentMethods: ["Dinheiro", "Cartão de Crédito", "Cartão de Débito"],
  },
  {
    id: 6,
    name: "Habib's",
    logo: "https://static-images.ifood.com.br/image/upload/t_high/logosgde/13198483-5fbc-422f-8285-69a95e5f406c/202103031135_vHtn_i.jpg",
    deliveryTime: "15-20 min",
    deliveryFee: "R$ 8,50",
    rating: 4.5,
    categories: ["Árabe", "Fast Food"],
    paymentMethods: ["Dinheiro", "Cartão de Crédito", "Cartão de Débito"],
  },
  {
    id: 7,
    name: "Dominos",
    logo: "https://static-images.ifood.com.br/image/upload/t_high/logosgde/13198483-5fbc-422f-8285-69a95e5f406c/202103031135_vHtn_i.jpg",
    deliveryTime: "15-20 min",
    deliveryFee: "R$ 8,50",
    rating: 4.5,
    categories: ["Árabe", "Fast Food"],
    paymentMethods: ["Dinheiro", "Cartão de Crédito", "Cartão de Débito"],
  },
];
